### ISSUE TITLE
Indentation irregularities

### ISSUE THREAD

**Issue by markovial** [StampyAI/GDocsRelatedThings#10]
The indent level on some answers does not render properly.

E.g.

It does not work on this answer: https://aisafety.info/?state=7602_
It does work on this answer: https://aisafety.info?state=6968_

**Comment by mruwnik** [comment]
I'm not sure whether this is possible - it looks like gdocs doesn't return info about the indentation level

**Comment by ChrisRimmer** [comment]
In theory this case is detectable as there are styling attributes added which we could detect, but it looks complex enough that I don't think I would say it's worthwhile. For this case, best move is just prefix the line with `>` so the parser (or more accurately, the markdown renderers which eat the parser output!) know it's a quote.

Indentation might be actually useful for other reasons elsewhere but given this is a quote, using correct syntax to say "this is a quote" rather than trying to do something that probably _looks_ vaguely like a quote in some ways seems preferable.
