### ISSUE TITLE
Feature Request: Semantically similar questions section

### ISSUE THREAD

**Issue by markovial** [StampyAI/GDocsRelatedThings#29]
There is the [alternate phrasings](https://docs.google.com/document/d/1at2ea7gTLuC0m9STYVUVFReMmFxVrHtbWKKmeEKHQDc/edit) column in coda.

In some call sometime there was a suggestion of having a parseable section called Alternate phrasings or semantically similar questions or something under which the author of the question/answer could write out the questions which are basically the same this as the current question but asked in a different way.

Each one of these questions could then be embedded into the alternate phrasings column automagically to help out with stuff like semantic search not finding similar questions, and reducing duplicates and stuff.

I dont really know if it should come before or after the related questions section... because then we would have to establish a convention for when one section begins and the other one officially ends.

**Comment by ccstan99** [comment]
Please just make sure editors understand that the questions should be indeed "different enough" so isn't already caught by the semantic search, i.e. check that it doesn't already come up as one of the top 5 in https://nlp.stampy.ai/. Otherwise, it clutters up the database and will actually degrade performance when https://github.com/StampyAI/stampy-nlp/issues/13 is implemented.
