### ISSUE TITLE
Add tags via gdocs

### ISSUE THREAD

**Issue by mruwnik** [StampyAI/GDocsRelatedThings#5]
Something like for related questions, but for tags, so editors can add them directly to the gdocs rather than having to manually add them through coda.

Might be hard to keep track of a specific set of tags, as there would probably be multiple ways of naming the same tag

**Comment by plexish** [comment]
Yeah, tags being more structured and sometimes being renamed is why I didn't go for this before. I think a bot command+living in coda might be best?

**Comment by robertskmiles** [comment]
If we can be terribly clever about this, having them in the doc would be
nicer, but yeah the interface design is tricky. We haven't found an easy
way to have drop-down menus work in docs afaict. If tags have urls, we can
require a bullet point list of tag urls, and that reduces the risk of typos
since people won't try to type a whole URL. But then the UX of adding tags
is pretty poor. Otherwise, we allow people to type them, and then have to
deal with all the near misses from similar tags. We could have non-existing
tags get automatically created, but then we need to merge them, or we can
have the parser highlight non-existing tags in red?

**Comment by plexish** [comment]
maybe just having us be a bot feature is fine?

**Comment by mruwnik** [comment]
seems good. https://github.com/StampyAI/stampy/issues/244 will add tagging to the bot
